---
nginx-ingress:
  controller:
    appprotect:
      enable: true
    appprotectdos:
      enable: true
    enableSnippets: true
    image:
      repository: ghcr.io/oteizaa/nginx-plus-ingress
      tag: 2.4.0-SNAPSHOT-7956665
    nginxplus: true
    nginxStatus:
      allowCidrs: 0.0.0.0/0
      port: 9000
    readyStatus:
      initialDelaySeconds: 30
    serviceAccount:
      imagePullSecretName: ghcr
  prometheus:
    create: true
