---
nginx-ingress:
  controller:
    logLevel: "info"

    initContainers:
      - name: setup-nap-dirs
        image: private-registry.nginx.com/nginx-ic-nap/nginx-plus-ingress:5.5.4-agent
        imagePullPolicy: Never
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        command:
          - sh
          - -c
          - |
            mkdir -p /opt/app_protect/bd_config/tables \
                     /opt/app_protect/var \
                     /opt/app_protect/bundles \
                     /opt/app_protect/config \
                     /var/run/app_protect \
                     /var/log/app_protect
            chmod -R 777 /opt/app_protect /var/run/app_protect /var/log/app_protect
        volumeMounts:
          - name: app-protect-bd-config
            mountPath: /opt/app_protect/bd_config
          - name: app-protect-var
            mountPath: /opt/app_protect/var
          - name: app-protect-bundles
            mountPath: /opt/app_protect/bundles
          - name: app-protect-config
            mountPath: /opt/app_protect/config
          - name: app-protect-run
            mountPath: /var/run/app_protect
          - name: app-protect-log
            mountPath: /var/log/app_protect

    volumes:
      - name: app-protect-bd-config
        emptyDir: {}
      - name: app-protect-var
        emptyDir: {}
      - name: app-protect-bundles
        emptyDir: {}
      - name: app-protect-config
        emptyDir: {}
      - name: app-protect-run
        emptyDir: {}
      - name: app-protect-log
        emptyDir: {}

    volumeMounts:
      - name: app-protect-bd-config
        mountPath: /opt/app_protect/bd_config
      - name: app-protect-var
        mountPath: /opt/app_protect/var
      - name: app-protect-bundles
        mountPath: /opt/app_protect/bundles
      - name: app-protect-config
        mountPath: /opt/app_protect/config
      - name: app-protect-run
        mountPath: /var/run/app_protect
      - name: app-protect-log
        mountPath: /var/log/app_protect

    readinessProbe:
      custom: true
    readyStatus:
      enable: false

    appprotect:
      enable: true
      v5: true
      securityContext:
        readOnlyRootFilesystem: false

      enforcer:
        image:
          repository: private-registry.nginx.com/nap/waf-enforcer        
          tag: "5.6.0"
          pullPolicy: Never
        securityContext:
          runAsUser: 101
          runAsGroup: 101  
        volumeMounts:
          - name: app-protect-bd-config
            mountPath: /opt/app_protect/bd_config
          - name: app-protect-var
            mountPath: /opt/app_protect/var
          - name: app-protect-bundles
            mountPath: /opt/app_protect/bundles
          - name: app-protect-config
            mountPath: /opt/app_protect/config
          - name: app-protect-run
            mountPath: /var/run/app_protect
          - name: app-protect-log
            mountPath: /var/log/app_protect

      configManager:
        image:
          repository: private-registry.nginx.com/nap/waf-config-mgr
          tag: "5.6.0"
          pullPolicy: Never
        securityContext:
          runAsUser: 101
          runAsGroup: 101  
        env:
          - name: ENFORCER_HOST
            value: "127.0.0.1"
          - name: ENFORCER_PORT
            value: "50000"  
        volumeMounts:
          - name: app-protect-bd-config
            mountPath: /opt/app_protect/bd_config
          - name: app-protect-var
            mountPath: /opt/app_protect/var
          - name: app-protect-bundles
            mountPath: /opt/app_protect/bundles
          - name: app-protect-config
            mountPath: /opt/app_protect/config
          - name: app-protect-run
            mountPath: /var/run/app_protect
          - name: app-protect-log
            mountPath: /var/log/app_protect

    appprotectdos:
      enable: false

    enableSnippets: true

    image:
      repository: private-registry.nginx.com/nginx-ic-nap/nginx-plus-ingress
      tag: 5.5.4-agent
      pullPolicy: Never

    nginxplus: true

    extraArgs:
      - -app-protect-enforcer-address=unix:/var/run/app_protect/bd_enforcer.sock

    mgmtConfigMap:
      enable: true
      name: "nginx-ingress/nginx-plus-ingress-nginx-ingress"

    nginxStatus:
      allowCidrs: 0.0.0.0/0
      port: 9000

    serviceAccount:
      imagePullSecretName: ghcr

    service:
      customPorts:
        - port: 9114
          targetPort: service-insight
          nodePort: 31000
          protocol: TCP
          name: service-insight
        - port: 9000
          targetPort: 9000
          nodePort: 32000
          protocol: TCP
          name: nginx-status

    nginxAgent:
      enable: true
      dataplaneKeySecretName: nginx-one-dataplane-key

  prometheus:
    create: true
  serviceInsight:
    create: true
