---
nginx-ingress:
  controller:
    logLevel: "info"

    # 1. Preparamos las carpetas con el initContainer y el volumen compartido
    initContainers:
      - name: setup-nap-dirs
        image: private-registry.nginx.com/nginx-ic-nap/nginx-plus-ingress:5.5.4-agent
        imagePullPolicy: Never
        securityContext:
          runAsUser: 0       # <--- CAMBIO CLAVE: Permite crear directorios en /opt/
          runAsGroup: 0
        command: ['sh', '-c', 'mkdir -p /opt/app_protect/bd_config/tables /opt/app_protect/var /opt/app_protect/bundles && chmod -R 777 /opt/app_protect']
        volumeMounts:
          - name: app-protect-bd-config
            mountPath: /opt/app_protect/bd_config
          - name: app-protect-var
            mountPath: /opt/app_protect/var
          - name: app-protect-bundles
            mountPath: /opt/app_protect/bundles

    volumes:
      - name: app-protect-bd-config
        emptyDir: {}
      - name: app-protect-var
        emptyDir: {}
      - name: app-protect-bundles
        emptyDir: {}

    volumeMounts:
      - name: app-protect-bd-config
        mountPath: /opt/app_protect/bd_config
      - name: app-protect-var
        mountPath: /opt/app_protect/var
      - name: app-protect-bundles
        mountPath: /opt/app_protect/bundles

    # 2. Desactivar el Readiness probe de Kubernetes
    readinessProbe:
      custom: true
    readyStatus:
      enable: false

    # 3. NOMBRES CORREGIDOS DE APP PROTECT V5 (wafEnforcer y wafConfigMgr)
    appprotect:
      enable: true
      v5: true
      securityContext:
        readOnlyRootFilesystem: false
      enforcer:
        image:
          repository: private-registry.nginx.com/nap/waf-enforcer        
          tag: "5.6.0"
          pullPolicy: Never
      configManager:
        image:
          repository: private-registry.nginx.com/nap/waf-config-mgr
          tag: "5.6.0"
          pullPolicy: Never

    appprotectdos:
      enable: false

    enableSnippets: true

    image:
      repository: private-registry.nginx.com/nginx-ic-nap/nginx-plus-ingress
      tag: 5.5.4-agent
      pullPolicy: Never

    nginxplus: true

    extraArgs:
      - -app-protect-enforcer-address=127.0.0.1:50000

    mgmtConfigMap:
      enable: true
      name: "nginx-ingress/nginx-plus-ingress-nginx-ingress"

    nginxStatus:
      allowCidrs: 0.0.0.0/0
      port: 9000

    serviceAccount:
      imagePullSecretName: ghcr

    service:
      customPorts:
        - port: 9114
          targetPort: service-insight
          nodePort: 31000
          protocol: TCP
          name: service-insight
        - port: 9000
          targetPort: 9000
          nodePort: 32000
          protocol: TCP
          name: nginx-status

    nginxAgent:
      enable: true
      dataplaneKeySecretName: nginx-one-dataplane-key

  prometheus:
    create: true
  serviceInsight:
    create: true
